import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home(data, countries) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Covid Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.headersInfo}>
        <p>Latest update: {data.date}</p>

        <p>
          Countries With Less Than 5000 Confirmed Cases: {data.countries.length}
        </p>
      </div>
      <p className={styles.headersTitle}>
        Countries With The Lowest Confirmed Cases
      </p>
      <div className={styles.countries}>
        {data.countries.map((country) => {
          return (
            <Link key={country.ID} href={"/" + country.Slug}>
              <a>
                <div className={styles.countriesCard}>
                  <img
                    src={
                      "https://flagcdn.com/" +
                      country.CountryCode.toLowerCase() +
                      ".svg"
                    }
                    alt={country.Country}
                  />
                  <p className={styles.countryName}>
                    {country.Country} ({country.CountryCode})
                  </p>
                  <div className={styles.countryInfo}>
                    <span className={styles.textInfo}>
                      Confirmed{" "}
                      <span className={styles.numberInfo}>
                        {country.TotalConfirmed}
                      </span>
                    </span>
                    <span className={styles.textInfo}>
                      Recovered{" "}
                      <span className={styles.numberInfo}>
                        {country.TotalRecovered}
                      </span>
                    </span>
                    <span className={styles.textInfo}>
                      Deaths{" "}
                      <span className={styles.numberInfo}>
                        {country.TotalDeaths}
                      </span>
                    </span>
                  </div>
                </div>
              </a>
            </Link>
          );
        })}
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const res = await fetch("https://api.covid19api.com/summary");
  const data = await res.json();
  const countries = await data.Countries.filter(
    (country) => country.TotalConfirmed < 5000
  );
  countries.sort((a, b) => (a.TotalConfirmed > b.TotalConfirmed ? 1 : -1));
  const date = await data.Date.split("T")[0];
  return {
    props: { data, countries, date },
  };
}
